### ISSUE TITLE
似乎没有考虑直接上传到各个云存储

### ISSUE THREAD

**Issue by zeroone2005** [namet117/oss#1]
我看你都是服务器上的文件上传到云存储，而不是前端直接上传到云存储。

**Comment by namet117** [comment]
是的，这是一个给服务端使用的库。

**Comment by zeroone2005** [comment]
现在你只完成了阿里云的接口吗

**Comment by namet117** [comment]
嘿嘿，暂时是的。
目前正在重写整个项目，不再使用各个平台的sdk，全部都自己实现。再发布的时候会有华为云和阿里云。
